# Generated by Django 4.2.2 on 2023-11-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_car_brand_alter_car_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default='', max_length=40),
        ),
    ]
