# Generated by Django 4.2.2 on 2023-12-31 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0007_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
                ('available_seats', models.PositiveSmallIntegerField()),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='travel.city')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('origin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='travel.city')),
            ],
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
