# Generated by Django 4.2.2 on 2023-12-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_rename_traveldetails_journeydetails_travel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travel',
            new_name='Journeys',
        ),
        migrations.AlterField(
            model_name='journeydetails',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='travel.userprofile'),
        ),
    ]
