# Generated by Django 4.2.2 on 2024-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_journeydetails_passengers_delete_journeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
