# Generated by Django 4.2.2 on 2024-01-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_journeydetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydetails',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_journeys', to='travel.city'),
        ),
        migrations.AlterField(
            model_name='journeydetails',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_journeys', to='travel.userprofile'),
        ),
        migrations.AlterField(
            model_name='journeydetails',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_journeys', to='travel.city'),
        ),
        migrations.AlterField(
            model_name='journeydetails',
            name='passengers',
            field=models.ManyToManyField(related_name='journeys_as_passenger', to='travel.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='journeydetails',
            constraint=models.UniqueConstraint(fields=('date', 'driver'), name='unique_journey_for_driver_and_date'),
        ),
    ]
