# Generated by Django 4.2.2 on 2024-01-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_journeydetails_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydetails',
            name='seat_price',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
