# Generated by Django 4.2.2 on 2024-01-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_journeydetails_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydetails',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
