# Generated by Django 4.2.30 on 2026-07-20 23:48

from django.db import migrations

# Plain data — the source of truth for our seed.
CALIFORNIA_CITIES = [
    "Los Angeles", "San Francisco", "San Diego", "Sacramento", "San Jose",
    "Fresno", "Long Beach", "Oakland", "Bakersfield", "Santa Barbara",
]

def seed_cities(apps, schema_editor):
    # get_model gives the *historical* City — safe even if the model changes later.
    City = apps.get_model('travel', 'City')
    for name in CALIFORNIA_CITIES:
        # get_or_create makes this idempotent: re-running never duplicates.
        City.objects.get_or_create(city_name=name)

def unseed_cities(apps, schema_editor):
    # The reverse: makes the migration undoable (migrate travel 0015).
    City = apps.get_model('travel', 'City')
    City.objects.filter(city_name__in=CALIFORNIA_CITIES).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('travel', '0015_journeydetails_isactive'),
    ]
    operations = [
        migrations.RunPython(seed_cities, unseed_cities),
    ]

